language: node_js
node_js:
  - node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: sOE295lKk1A/chsPqenb5ucuir87mXYKY+dw6yEVuv0D7I+jnmus7jtoMADRinFDxMkHvGoSeuZzyJ2pfduH8ms/J81/gY8v5r2LnnQ7JrLtxP2v0RejBQJFghyg+cWf/3t9z3IZEX3hkw1zmfuzLQ9IaZMFjUgxKQKdRYHK/5FNv5rK9pFpjyEJxlZk32LmxTZzqwIeLp+Cw3bBUhh3kRbnHl6ckMN1mn9D/odXtBoK6TAoG2biP3UT20nRu6FXuG+MwARhp6wVXGieMkQRMPdfLc1iJx9aSiu6JXl6XATpiv0rd1cfOeK0axbTO0bd87BQzXHpTck/PV2PvdTqgYoACyBDHo3xx07/8RjZrAxBnfF4ahZsZwtjmi1GzZLdTW/UBquR1HVpKwqSKmnwdz/GHxqq7emjv9gzqw5zDPnbD4HZUi3q8J/YTrK4BOej5xdkR8jaK+CHgW46OKxXacLVu4ME2ocr9EiNGvqReDOt8pawdvsG2d+sATl7IPey8o/8MiSuPZZ9o5u8lK3Wa0+ARcKEoCSkhslWtThwnT+bPjQdQjdaS/7CE/dx4vQTdLkCNp6eIdR495TiRf/DGv/mJaJWxSGsKAa6a7KYjjALN6/uz+/vPyKf1Y5yyHyujXUwO/BioT2WrgIZr3iPwDsYHufQkjuD8dxWqujyTRM=
  app: vail-mtb
  skip_cleanup: true
